# Generated by Django 2.2.5 on 2020-03-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20200310_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='message',
            field=models.TextField(default='', max_length=200),
        ),
    ]
