# Generated by Django 2.2.5 on 2020-03-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20200310_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='message',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
